### ISSUE TITLE
Decide on overarching dataset / problem / narrative we want to guide our lesson

### ISSUE THREAD

**Issue by peterlaurin** [carpentries-incubator/R-help-reprexes#15] opened 2024-08-20 19:08 UTC
We need a narrative to guide examples and issues learners might experience in getting stuck and getting help with R. Ideally, this narrative should be able to encompass several episodes and motivate examples and exercises

**Comment by xortizross** [comment] 2024-08-30 00:10
Note that this is being worked on under scripts/example_narrative.R

**Comment by kaijagahm** [comment] 2024-09-25 21:51
Duplicate of #10

**Closed by kaijagahm** 2024-09-25 21:51 UTC
Labels: workflow
